package com.stratum.core.domain.art

import com.stratum.core.domain.content.BiomeDefinition
import com.stratum.core.domain.content.ContentPack
import com.stratum.core.domain.world.BlockMaterial
import com.stratum.core.domain.world.BlockType

/**
 * The bounded set of ingredients one region is drawn from.
 *
 * This is the cheap half of the AI plan and the reason the expensive half is
 * not needed. Nobody generates terrain art: a region gets a handful of ground
 * swatches, a handful of prop silhouettes, one landmark and one weather, and
 * the generator's placement rules turn those few ingredients into a hundred
 * thousand cells that still look authored. Generation is spent on the kit, once,
 * not on the acre.
 *
 * A kit is deliberately small. A region with thirty prop families is a region
 * with no identity, and the discipline of "eight swatches, five silhouettes,
 * one landmark, one weather" is doing most of the work that the palette and the
 * lighting get the credit for.
 */
data class BiomeArtKit(
    val biomeId: String,
    /** The few colours this region's ground snaps to. */
    val groundRamp: List<Long> = emptyList(),
    /** Which silhouette family each of the region's props is drawn as. */
    val propFamilies: Map<String, PropSilhouette> = emptyMap(),
    /**
     * The one thing in the region you can see from across the map.
     *
     * A region of evenly good forest is a region with nowhere to go. One
     * enormous sacred tree, one bronze gate, one collapsed mine mouth is what
     * turns a field into a place, and it costs one asset.
     */
    val landmarkBlockId: String? = null,
    /** Overrides the style's weather for this region only. */
    val atmosphere: AtmosphereRule? = null,
    /** What danger is allowed to be coloured here. */
    val threatAccent: Long? = null,
    /** What the region holds sacred, and the only other thing allowed to glow. */
    val sacredAccent: Long? = null,
    /** Pushed into every shadowed face, which is how a region gets a mood. */
    val shadowTint: Long? = null,
    /** Words describing this region to an image model. See [ArtBible]. */
    val subject: String = "",
) {
    companion object {

        /**
         * Reads a kit out of a region that was never written with one in mind.
         *
         * Every pack the game can load — built in, generated by a model, or
         * imported from a file — already says what its ground is made of, what
         * grows on it and what it holds sacred. That is a kit; it is just
         * spelled as simulation rules. Deriving rather than requiring is what
         * lets art direction apply to a pack a model invented ninety seconds
         * ago, which is the only way the promptable half of this ever works.
         */
        fun derive(biome: BiomeDefinition, blocks: Map<String, BlockType>): BiomeArtKit {
            val ground = listOfNotNull(
                blocks[biome.surfaceBlockId],
                blocks[biome.subsurfaceBlockId],
                blocks[biome.bedrockFillerBlockId],
            )
            val scattered = biome.scatter.mapNotNull { blocks[it.blockId] } +
                biome.scatter.mapNotNull { rule -> rule.capBlockId?.let { blocks[it] } }
            val deposited = biome.deposits.mapNotNull { blocks[it.blockId] }

            return BiomeArtKit(
                biomeId = biome.id,
                groundRamp = rampOf(ground),
                propFamilies = scattered.associate { it.id to PropSilhouette.forMaterial(it) },
                landmarkBlockId = landmarkOf(scattered + deposited),
                atmosphere = weatherOf(biome, ground, scattered),
                threatAccent = null,
                sacredAccent = (scattered + deposited)
                    .firstOrNull { it.material == BlockMaterial.RITUAL || it.lightEmission > 0 }
                    ?.accentColor
                    ?.takeIf { Tint.alpha(it) > 0 },
                shadowTint = null,
                subject = biome.description.ifBlank { biome.name },
            )
        }

        /** Derives a kit for every region a pack ships, in one call. */
        fun deriveAll(pack: ContentPack): Map<String, BiomeArtKit> {
            val blocks = pack.blocks.associateBy { it.id }
            return pack.biomes.associate { it.id to derive(it, blocks) }
        }

        /**
         * Builds a short ramp out of a region's own materials.
         *
         * Three source colours, each at a lit, a mid and a shadowed value, is
         * nine — enough that ground does not band visibly, few enough that it
         * reads as chosen. Taking them from the pack's blocks rather than from
         * the style is deliberate: the style says how colour behaves, the pack
         * still says which colours those are.
         */
        private fun rampOf(ground: List<BlockType>): List<Long> =
            ground.flatMap { block ->
                listOf(
                    Tint.scale(block.topColor, 1.12f),
                    block.topColor,
                    Tint.scale(block.sideColor, 0.82f),
                )
            }.distinct()

        /**
         * Picks the one block a region should build its landmark from.
         *
         * Light first, then ritual, then the rarest deposit. A region's
         * landmark ought to be the thing the region is *about*, and in a
         * simulation the thing a region is about is reliably the thing that
         * glows or the thing that is hard to get.
         */
        private fun landmarkOf(candidates: List<BlockType>): String? =
            candidates.maxByOrNull { block ->
                block.lightEmission * 4 +
                    (if (block.material == BlockMaterial.RITUAL) 10 else 0) +
                    (if (block.material == BlockMaterial.ORE) 3 else 0) +
                    block.requiredTier
            }?.id

        /**
         * Guesses what hangs in the air, from what the region is made of.
         *
         * Not a lookup table of region names: a pack generated this morning has
         * names nothing can match. Foliage and low light means spores, heat and
         * ash means embers, deep and dark means dust. Wrong occasionally,
         * present always, and a style or a pack can override it by supplying
         * its own [AtmosphereRule].
         */
        private fun weatherOf(
            biome: BiomeDefinition,
            ground: List<BlockType>,
            props: List<BlockType>,
        ): AtmosphereRule? {
            val lit = props.any { it.lightEmission > 0 }
            val leafy = props.any { it.material == BlockMaterial.FOLIAGE || it.material == BlockMaterial.WOOD }
            val wet = ground.any { it.material == BlockMaterial.LIQUID } || biome.heightBias < -1
            val dark = biome.ambientLight <= 6

            val kind = when {
                lit && dark -> MoteKind.EMBERS
                leafy && biome.ambientLight >= 10 -> MoteKind.FIREFLIES
                leafy -> MoteKind.SPORES
                wet -> MoteKind.MIST
                dark -> MoteKind.DUST
                else -> return null
            }
            return AtmosphereRule(
                moteKind = kind,
                moteDensity = if (dark) 26 else 38,
                moteColor = props.firstOrNull { it.lightEmission > 0 }?.accentColor
                    ?: ground.firstOrNull()?.accentColor
                    ?: 0xFFF0C862,
            )
        }
    }
}
