package com.stratum.core.data.ai

import android.util.Base64
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.stratum.core.domain.ai.ClipRequest
import com.stratum.core.domain.ai.GeneratedClip
import com.stratum.core.domain.ai.GenerationException
import com.stratum.core.domain.ai.GenerationObserver
import com.stratum.core.domain.ai.GenerationStage
import com.stratum.core.domain.ai.ImageReference
import com.stratum.core.domain.ai.VideoModelPort
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.concurrent.TimeUnit

/**
 * Asks a video endpoint for a clip, and waits for it.
 *
 * Three calls rather than one, because generating video is slow enough that no
 * provider holds a connection open for it. Post the request and a job id comes
 * back immediately; poll the job until it says it has finished; fetch the bytes
 * from the job's own content endpoint. The port hides all of that behind one
 * suspend function, which is the shape the rest of the pipeline already speaks.
 *
 * A warning that cost real money to learn: this API accepts fields it does not
 * know and says nothing. A request carrying an invented field name came back
 * 202 with a job id and generated a clip, silently ignoring it. So a typo in
 * [FRAME_IMAGES] or in a frame type does not fail — it produces a clip that
 * simply was not conditioned on anything, which looks like a plausible result
 * and is not the one that was asked for. Every field name here was verified
 * against a real generation by checking that the returned clip actually started
 * on the drawing it was given.
 */
class OpenRouterVideoModel(
    private val configProvider: () -> ProviderConfig,
    private val client: OkHttpClient = defaultClient(),
    private val moshi: Moshi = Moshi.Builder().build(),
    /** How often to ask whether the job has finished. */
    private val pollInterval: Long = POLL_INTERVAL_MS,
    /** How long to wait before giving up on a job that never finishes. */
    private val timeout: Long = TIMEOUT_MS,
) : VideoModelPort {

    override suspend fun generateClip(
        request: ClipRequest,
        observer: GenerationObserver,
    ): Result<GeneratedClip> = withContext(Dispatchers.IO) {
        observer.onStage(GenerationStage.PREPARING)
        val config = configProvider()
        if (config.apiKey.isBlank()) {
            observer.onStage(GenerationStage.FAILED)
            return@withContext Result.failure(
                GenerationException("No API key is configured for ${config.displayName}"),
            )
        }

        val base = config.baseUrl.trimEnd('/')
        val model = request.modelId ?: config.videoModel

        runCatching {
            observer.onStage(GenerationStage.SENDING)
            val jobId = submit(base, config, model, request)
            observer.onStage(GenerationStage.WAITING)
            awaitCompletion(base, config, jobId)
            val bytes = download(base, config, jobId)
            observer.onStage(GenerationStage.DONE)
            GeneratedClip(bytes = bytes, mimeType = MIME_MP4)
        }.onFailure { observer.onStage(GenerationStage.FAILED) }
    }

    /** Posts the job and returns its id. */
    private fun submit(
        base: String,
        config: ProviderConfig,
        model: String,
        request: ClipRequest,
    ): String {
        val frames = buildList {
            request.firstFrame?.let { add(frameOf(it, FIRST_FRAME)) }
            // Only sent when there is one. A provider that ignores it leaves
            // the far end of the clip to drift; a provider that rejects an
            // empty list would fail every text-only request.
            request.lastFrame?.let { add(frameOf(it, LAST_FRAME)) }
        }
        val payload = moshi.adapter(ClipRequestDto::class.java).toJson(
            ClipRequestDto(
                model = model,
                prompt = request.prompt,
                duration = request.durationSeconds,
                resolution = resolutionOf(request),
                aspect_ratio = aspectOf(request),
                // Off, and it halves the bill. Audio is generated by default
                // and charged at twice the rate, for a soundtrack a sprite
                // sheet discards.
                generate_audio = request.generateAudio,
                frame_images = frames.ifEmpty { null },
            ),
        )

        val httpRequest = Request.Builder()
            .url("$base/videos")
            .headers(config)
            .post(payload.toRequestBody(JSON_MEDIA_TYPE))
            .build()

        client.newCall(httpRequest).execute().use { response ->
            val body = response.body?.string().orEmpty()
            if (!response.isSuccessful) throw failureFor(response.code, body)
            val job = moshi.adapter(ClipJobDto::class.java).fromJson(body)
            return job?.id
                ?: throw GenerationException("The provider accepted the clip but gave no job id")
        }
    }

    /** Polls until the job finishes, fails, or outlives its welcome. */
    private suspend fun awaitCompletion(base: String, config: ProviderConfig, jobId: String) {
        val deadline = System.currentTimeMillis() + timeout
        while (true) {
            val httpRequest = Request.Builder()
                .url("$base/videos/$jobId")
                .headers(config)
                .get()
                .build()
            val job = client.newCall(httpRequest).execute().use { response ->
                val body = response.body?.string().orEmpty()
                if (!response.isSuccessful) throw failureFor(response.code, body)
                moshi.adapter(ClipJobDto::class.java).fromJson(body)
            }
            when (job?.status?.lowercase()) {
                STATUS_COMPLETED -> return
                STATUS_FAILED -> throw GenerationException(
                    job.error ?: "The provider could not generate the clip",
                )
            }
            if (System.currentTimeMillis() >= deadline) {
                // Retryable: the job may well have been fine and merely slow,
                // and a run of a dozen clips should not lose the rest because
                // one of them took longer than expected.
                throw GenerationException(
                    "The clip was still generating after ${timeout / 1000}s",
                    retryable = true,
                )
            }
            delay(pollInterval)
        }
    }

    private fun download(base: String, config: ProviderConfig, jobId: String): ByteArray {
        val httpRequest = Request.Builder()
            // index=0 because one request makes one clip. The field exists for
            // providers that return several, which none of these do.
            .url("$base/videos/$jobId/content?index=0")
            .headers(config)
            .get()
            .build()
        client.newCall(httpRequest).execute().use { response ->
            if (!response.isSuccessful) {
                throw failureFor(response.code, response.body?.string().orEmpty())
            }
            val bytes = response.body?.bytes()
            if (bytes == null || bytes.isEmpty()) {
                throw GenerationException("The finished clip downloaded as nothing")
            }
            return bytes
        }
    }

    private fun frameOf(reference: ImageReference, type: String) = FrameImageDto(
        type = IMAGE_URL,
        image_url = ImageUrlDto(url = reference.asDataUrl()),
        frame_type = type,
    )

    /**
     * The picture, inline.
     *
     * A data URL rather than a hosted one, which the documented example uses.
     * Verified against a real generation: the clip came back starting on the
     * drawing that was sent, so it is read rather than quietly dropped — which
     * matters more here than usual, since an ignored field is a silent 202.
     */
    private fun ImageReference.asDataUrl(): String =
        "data:$mimeType;base64," + Base64.encodeToString(bytes, Base64.NO_WRAP)

    /** The nearest published resolution at or above what was asked for. */
    private fun resolutionOf(request: ClipRequest): String {
        val longest = maxOf(request.width, request.height)
        return when {
            longest <= 480 -> "480p"
            longest <= 720 -> "720p"
            else -> "1080p"
        }
    }

    private fun aspectOf(request: ClipRequest): String = when {
        request.width == request.height -> "1:1"
        request.width > request.height -> "16:9"
        else -> "9:16"
    }

    private fun Request.Builder.headers(config: ProviderConfig) = apply {
        addHeader("Authorization", "Bearer ${config.apiKey}")
        addHeader("Content-Type", "application/json")
        addHeader("HTTP-Referer", config.refererUrl)
        addHeader("X-Title", config.appTitle)
    }

    /**
     * Turns a status code into something a person can act on, and says whether
     * to try again.
     *
     * The duration case earns its own line: the provider rejects a length it
     * does not sell rather than rounding to one, and its message names the set
     * it does sell, which is the only place that list appears at request time.
     */
    private fun failureFor(code: Int, body: String): GenerationException = when (code) {
        400 -> GenerationException("The provider refused the clip: ${body.take(300)}")
        401, 403 -> GenerationException("The API key was rejected. Check it in settings.", fatal = true)
        402 -> GenerationException("The provider reports no remaining credit.", fatal = true)
        404 -> GenerationException(
            "That video model is not available. Video models are listed separately " +
                "from the others, under /videos/models.",
            fatal = true,
        )
        429 -> GenerationException("The provider is rate limiting.", retryable = true)
        in 500..599 -> GenerationException("The provider is having trouble (HTTP $code).", retryable = true)
        else -> GenerationException("The provider refused the request (HTTP $code): ${body.take(200)}")
    }

    private companion object {
        const val MIME_MP4 = "video/mp4"
        const val IMAGE_URL = "image_url"

        /** The two ends a clip can be pinned to, exactly as the provider spells them. */
        const val FIRST_FRAME = "first_frame"
        const val LAST_FRAME = "last_frame"
        const val FRAME_IMAGES = "frame_images"

        /** The job states worth acting on; anything else means keep waiting. */
        const val STATUS_COMPLETED = "completed"
        const val STATUS_FAILED = "failed"

        const val POLL_INTERVAL_MS = 5_000L

        /** Measured at about a minute a clip; this is generous rather than tight. */
        const val TIMEOUT_MS = 300_000L

        val JSON_MEDIA_TYPE = "application/json".toMediaType()

        fun defaultClient(): OkHttpClient = OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            // A finished clip is several megabytes, and the download is one
            // request rather than a stream the caller can resume.
            .readTimeout(180, TimeUnit.SECONDS)
            .writeTimeout(120, TimeUnit.SECONDS)
            .build()
    }
}

@JsonClass(generateAdapter = true)
internal data class ClipRequestDto(
    val model: String,
    val prompt: String,
    val duration: Int,
    val resolution: String,
    val aspect_ratio: String,
    val generate_audio: Boolean,
    val frame_images: List<FrameImageDto>?,
)

@JsonClass(generateAdapter = true)
internal data class FrameImageDto(
    val type: String,
    // Reuses the image adapter's, which is the same shape in the same package.
    val image_url: ImageUrlDto,
    /** "first_frame" or "last_frame". Anything else is accepted and ignored. */
    val frame_type: String,
)

@JsonClass(generateAdapter = true)
internal data class ClipJobDto(
    val id: String?,
    val status: String?,
    val error: String? = null,
)
