package com.stratum.engine.world

import com.stratum.core.domain.world.BlockPos
import com.stratum.core.domain.world.BlockRegistry
import com.stratum.core.domain.world.Chunk
import com.stratum.core.domain.world.ChunkPos
import com.stratum.core.domain.world.TerrainGenerator
import com.stratum.core.domain.world.WorldConfig
import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicInteger
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/** Ground generated ahead on worker threads is the ground the game thread would have made, and never blocks it. */
class BackgroundGenerationTest {

    private val pool = Executors.newFixedThreadPool(2)

    @AfterTest fun stop() { pool.shutdownNow() }

    /** A slow, pure generator that remembers which threads it ran on. */
    private class Slow(val millis: Long = 15) : TerrainGenerator {
        val threads: MutableSet<String> = java.util.concurrent.ConcurrentHashMap.newKeySet()
        val made = AtomicInteger()
        override fun generate(pos: ChunkPos, registry: BlockRegistry): Chunk {
            threads += Thread.currentThread().name
            made.incrementAndGet()
            Thread.sleep(millis)
            return Chunk(pos).also { c -> for (x in 0 until Chunk.SIZE) for (y in 0 until Chunk.SIZE) for (z in 0..((pos.x * 7 + pos.y * 3 + x + y) and 7)) c.setBlock(x, y, z, 1) }
        }
    }

    private val config = WorldConfig(simulationRadius = 4)

    private fun walk(world: StreamingWorld, steps: Int, settle: Boolean): Long {
        var worst = 0L
        for (i in 0..steps) {
            val start = System.nanoTime()
            world.focusOn(BlockPos(i * 4, i, 5), urgentRadius = 1)
            world.pump(2)
            worst = maxOf(worst, System.nanoTime() - start)
            if (settle) Thread.sleep(20)
        }
        // Then stand still until the whole window is in.
        var guard = 0
        while (world.pendingCount > 0 && guard++ < 2_000) { world.pump(2); Thread.sleep(2) }
        return worst
    }

    @Test
    fun `chunks made on workers are the chunks the game thread makes`() {
        val here = StreamingWorld(TestContent.registry, Slow(0), config, workers = null)
        val there = StreamingWorld(TestContent.registry, Slow(0), config, workers = pool)
        walk(here, 40, settle = false); walk(there, 40, settle = true)
        assertEquals(here.loadedChunks.map { it.pos }.toSet(), there.loadedChunks.map { it.pos }.toSet())
        for (c in here.loadedChunks) assertContentEquals(c.exportBlocks(), there.chunkAt(c.pos)!!.exportBlocks(), "chunk ${c.pos}")
    }

    @Test
    fun `walking does not generate on the game thread once the workers are ahead`() {
        val slow = Slow(15)
        val world = StreamingWorld(TestContent.registry, slow, config, workers = pool)
        world.focusOn(BlockPos(0, 0, 5)) // the whole first window, at once, as a new world does
        var guard = 0
        while (world.pendingCount > 0 && guard++ < 2_000) { world.pump(2); Thread.sleep(2) }
        val before = slow.made.get()
        slow.threads.clear()
        // Walk east at a stroll, one chunk every so often: the queued ring is made ahead on the workers.
        val worst = walk(world, 60, settle = true)
        assertTrue(slow.made.get() > before, "nothing new was generated")
        assertTrue(slow.threads.none { it == Thread.currentThread().name }, "the game thread generated: ${slow.threads}")
        assertTrue(worst < 15_000_000L, "a tick waited ${worst / 1_000_000} ms for ground")
    }

    @Test
    fun `edited chunks come back as they were left, never regenerated by a worker`() {
        val world = StreamingWorld(TestContent.registry, Slow(0), config, workers = pool)
        world.focusOn(BlockPos(0, 0, 5))
        world.setBlock(BlockPos(3, 3, 30), 2)
        world.focusOn(BlockPos(400, 0, 5)) // far away: the edited chunk unloads
        world.focusOn(BlockPos(0, 0, 5), urgentRadius = 0)
        var guard = 0
        while (world.pendingCount > 0 && guard++ < 2_000) { world.pump(2); Thread.sleep(2) }
        assertEquals(2, world.blockIndexAt(BlockPos(3, 3, 30)))
    }

    @Test
    fun `a retuned generator's ground replaces what workers made for the old one`() {
        var flavour = 1
        val generator = object : TerrainGenerator {
            override fun generate(pos: ChunkPos, registry: BlockRegistry) = Chunk(pos).also { it.setBlock(0, 0, 0, flavour) }
        }
        val world = StreamingWorld(TestContent.registry, generator, config, workers = pool)
        world.focusOn(BlockPos(0, 0, 5), urgentRadius = 0)
        world.pump(2)
        flavour = 2
        world.regenerate(urgentRadius = 0)
        var guard = 0
        while (world.pendingCount > 0 && guard++ < 2_000) { world.pump(2); Thread.sleep(2) }
        assertTrue(world.loadedChunks.all { it.blockAt(0, 0, 0) == 2 }, "old ground survived the retune")
    }
}
